### ISSUE TITLE
Running on Windows -  no such file or directory, open '/usr/src/app/package.json'

### ISSUE THREAD

**Issue by remster85** [KumarAbhirup/dockerized#2]
Thanks a lot Kumar for your tutorial.  
I am fairly new to Docker and encounter some issues to browse the website.   
I am running docker on my windows 10 Home with Docker tools.

When I execute docker-compose, I got the following error.
```
remid@LAPTOP-MINGW64 /c/users/remid/dockerized (master)
$  docker-compose up
Starting dockerized_nextjs_1 ... done                                               Attaching to dockerized_nextjs_1
nextjs_1  | npm ERR! code ENOENT
nextjs_1  | npm ERR! syscall open
nextjs_1  | npm ERR! path /usr/src/app/package.json
nextjs_1  | npm ERR! errno -2
nextjs_1  | npm ERR! enoent ENOENT: no such file or directory, open '/usr/src/app/package.json'
nextjs_1  | npm ERR! enoent This is related to npm not being able to find a file.
nextjs_1  | npm ERR! enoent
nextjs_1  |
nextjs_1  | npm ERR! A complete log of this run can be found in:
nextjs_1  | npm ERR!     /root/.npm/_logs/2020-03-29T23_25_25_944Z-debug.log
dockerized_nextjs_1 exited with code 254
```

I have also tried to build the image with docker build with no error:  
```
docker build . project

Step 10/10 : CMD "npm" "run" "dev"
 ---> Running in 9adcae1ef952
Removing intermediate container 9adcae1ef952
 ---> ec652f219f51
Successfully built ec652f219f51
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.```
```

It runs well, I can curl -I http://localhost:3000 with success from the container.  
```
remid@MINGW64 /c/users/remid/dockerized/packages/landingpage (master)
$ docker run  ec652f219f51

> with-typescript@1.0.0 dev /usr/src/app
> next

[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
> Using "webpackDevMiddleware" config function defined in next.config.js.
```

However, when trying to map the ports, I got the following error:

```
$ docker run  ec652f219f51 -p 3001:3000
[eval]:1
3001:3000
    ^

SyntaxError: Unexpected token ':'
    at new Script (vm.js:88:7)
    at createScript (vm.js:263:10)
    at Object.runInThisContext (vm.js:311:10)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_string.js:23:3
```

Thanks for your help.

**Comment by kumarabhirup** [comment]
Hmm, that is weird.

I don't have a Windows machine to reproduce on. As far as I know, Docker works best on Windows 10 Enterprise.

Very soon, will install a Windows Virtual Machine on my laptop and will let you know 🔥

Stay tuned!

**Comment by kumarabhirup** [comment]
Hey, @remster85! Thanks for posting this issue.

I failed to reproduce this issue on Windows.

Can you try this?

```
$ docker run  ec652f219f51 -p 3000:3000
```

Let me know what appears.

**Comment by remster85** [comment]
Same error

```
PS C:\Users\user> docker run  ec652f219f51 -p 3000:3000
[eval]:1
3000:3000
    ^

SyntaxError: Unexpected token ':'
    at new Script (vm.js:88:7)
    at createScript (vm.js:263:10)
    at Object.runInThisContext (vm.js:311:10)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_string.js:23:3
```

**Comment by kumarabhirup** [comment]
I think I understood where the problem is.

The file system in Linux and Mac supports `/`, 

while in Windows `\` is supported in the file URL.

https://github.com/KumarAbhirup/dockerized/blob/master/docker-compose.yml#L8-L11

Try changing the 
`context: packages/landingpage` 👉 `context: packages\landingpage`
`- ./packages/landingpage:/usr/src/app` 👉 `- .\packages\landingpage:/usr/src/app`.

I am not sure if `.\`  syntax is supported in Windows file system but I am guessing it does.

Let me know if it works.

**Comment by remster85** [comment]
Hi @KumarAbhirup, thanks for your help! I managed to get the 
`Welcome to the Dockerized App!` message using the url http://192.168.99.100:3000/.
I found this url from this [discussion](https://forums.docker.com/t/cant-connect-to-container-on-localhost-with-port-mapping/52716/7) and from [SOF](https://stackoverflow.com/questions/42866013/docker-toolbox-localhost-not-working).  It's a docker-tools specificity.

Using `docker-machine.exe ip` would return the IP address to target  
=> 192.168.99.100

The volume section of docker-compose.yml does not have any effect whether I use \ or / for the paths or even when I removed it, it still works as long as I use the IP address  http://192.168.99.100:3000.

I am wondering if those volumes are useful after all?

**Comment by kumarabhirup** [comment]
Very glad you found a solution 🙌

Yes, volumes are very useful for local development. 
If you want to work with Next.js Live Hot Reload, you need your volumes to be in sync with `.next` and `node_modules`...

I am not sure if Live Reload is working on Windows, you can try `/` and `\` for volumes and let me know what works!

**Comment by remster85** [comment]
Does it mean that I would be able to change the content of the container dynamically ?

**Comment by kumarabhirup** [comment]
To be honest, I am not sure about being able to "change the content of the container dynamically".

But I know that without volumes, live development will not be possible. It will work only in production then.

**Comment by Ebernn** [comment]
> When I execute docker-compose, I got the following error.

You probably have to run docker in a VM to use it on Windows 10 Home - OS built on a fat layer of slippery 💩
So forgetting to **mount your folder** will cause that `docker-compose` error (it happens to me from time to time).
Hope it helps (you or someone else), awesome repo Kumar 🔥
